pipeline {
    agent any

    stages {
        stage('Build PDFs') {
            steps {
                sh 'docker run -v $PWD/:/authorarchive logicalhacking:debian4isabelle sh -c "cd /authorarchive/examples && (for i in *.tex; do pdflatex \\$i; pdflatex \\$i; pdflatex \\$i;  done)"'
            }
        }
    }
} 

