pipeline:
  build:
    image: docker.io/texlive/texlive
    commands:
      - export ARTIFACT_DIR=$CI_WORKSPACE/.artifacts/$CI_REPO_NAME/$CI_BRANCH/$CI_BUILD_NUMBER/
      - mkdir -p $ARTIFACT_DIR
      - cd examples
      - curl http://www.entcs.org/generic.zip --output generic.zip
      - unzip -p generic.zip generic/entcs.cls > entcs.cls
      - rm generic.zip
      - latexmk -pdf
      - cp *.pdf $ARTIFACT_DIR
  deploy:
    image: docker.io/drillster/drone-rsync
    settings:
      hosts: [ "ci.logicalhacking.com"]
      port: 22
      source: .artifacts/$CI_REPO_NAME/*
      target: $CI_REPO_NAME
      include: [ "**.*"]
      key: 
        from_secret: artifacts_ssh
      user: artifacts


