pipeline:
  build:
    image: docker.io/texlive/texlive
    commands:
      - cd examples
      - curl http://www.entcs.org/generic.zip --output generic.zip
      - unzip -p generic.zip generic/entcs.cls > entcs.cls
      - rm generic.zip
      - latexmk -pdf
