pipeline:
  build:
    image: docker.io/texlive/texlive
    commands:
      - cd examples
      - wget http://www.entcs.org/generic.zip
      - unzip -p generic.zip generic/entcs.cls > entcs.cls
      - rm generic.zip
      - latexmk -pdf
