pipeline:
  build:
    image: docker.io/texlive/texlive
    commands:
      - export ARTIFACT_DIR=$CI_WORKSPACE/.artifacts/$CI_REPO/$CI_BRANCH/$CI_BUILD_NUMBER/
      - mkdir -p $ARTIFACT_DIR
      - cd examples
      - curl http://www.entcs.org/generic.zip --output generic.zip
      - unzip -p generic.zip generic/entcs.cls > entcs.cls
      - rm generic.zip
      - latexmk -pdf
      - latexmk -C
      - latexmk -lualatex
      - cp *.pdf $ARTIFACT_DIR
      - cd $ARTIFACT_DIR
      - cd ..
      - ln -s * latest
  deploy:
    image: docker.io/drillster/drone-rsync
    settings:
      hosts: [ "ci.logicalhacking.com"]
      port: 22
      source: .artifacts/$CI_REPO_OWNER/*
      target: $CI_REPO_OWNER
      include: [ "**.*"]
      key: 
        from_secret: artifacts_ssh
      user: artifacts
  notify:
    image: drillster/drone-email
    settings:
      host: smtp.0x5f.org
      username: woodpecker
      password: 
        from_secret: email
      from: ci@logicalhacking.com
    when:
      status: [ changed, failure ]

